package ConcatApp;


/**
* ConcatApp/Concat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Concat.idl
* Sunday, May 28, 2023 10:39:02 AM EDT
*/

public interface Concat extends ConcatOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Concat
