package ConcatApp;

/**
* ConcatApp/ConcatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Concat.idl
* Sunday, May 28, 2023 10:39:02 AM EDT
*/

public final class ConcatHolder implements org.omg.CORBA.portable.Streamable
{
  public ConcatApp.Concat value = null;

  public ConcatHolder ()
  {
  }

  public ConcatHolder (ConcatApp.Concat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ConcatApp.ConcatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ConcatApp.ConcatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ConcatApp.ConcatHelper.type ();
  }

}
