package ConcatApp;


/**
* ConcatApp/ConcatPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Concat.idl
* Sunday, May 28, 2023 10:39:02 AM EDT
*/

public abstract class ConcatPOA extends org.omg.PortableServer.Servant
 implements ConcatApp.ConcatOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("concat_string", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ConcatApp/Concat/concat_string
       {
         String s1 = in.read_string ();
         String s2 = in.read_string ();
         String $result = null;
         $result = this.concat_string (s1, s2);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ConcatApp/Concat:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Concat _this() 
  {
    return ConcatHelper.narrow(
    super._this_object());
  }

  public Concat _this(org.omg.CORBA.ORB orb) 
  {
    return ConcatHelper.narrow(
    super._this_object(orb));
  }


} // class ConcatPOA
