package ConcatApp;


/**
* ConcatApp/ConcatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Concat.idl
* Sunday, May 28, 2023 10:39:02 AM EDT
*/

public interface ConcatOperations 
{
  String concat_string (String s1, String s2);
} // interface ConcatOperations
