package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Sunday, May 28, 2023 9:40:28 AM EDT
*/

public interface CalculatorOperations 
{
  double getSum (double a, double b);
  double getDiff (double a, double b);
  double getMul (double a, double b);
  double getDiv (double a, double b);
} // interface CalculatorOperations
